CREATE DATABASE yousufDB;

USE yousufDB;

CREATE TABLE department (
DNUM INT PRIMARY KEY,
DNAME NVARCHAR(70),
SSN CHAR(9),
MHDATE DATE 
);



CREATE TABLE employee (
SSN CHAR(9) PRIMARY KEY,
FNAME NVARCHAR(50),
LNAME NVARCHAR(50),
GENDER CHAR(1),
BIRTHDATE DATE,
SUPERSSN CHAR(9),
DNUM INT,
FOREIGN KEY (SUPERSSN) REFERENCES employee(SSN),
FOREIGN KEY (DNUM) REFERENCES department(DNUM)
);

ALTER TABLE department
ADD CONSTRAINT HEADDEP FOREIGN KEY(SSN) REFERENCES employee(SSN);





CREATE TABLE dependent (
Name NVARCHAR(50) PRIMARY KEY,
SSN CHAR(9),
GENDER CHAR(1),
BIRTHDATE DATE,
FOREIGN KEY (SSN) REFERENCES employee(SSN)
);



CREATE TABLE DEARTMENTLOC(
LOCATION NVARCHAR(50) PRIMARY KEY,
DNUM INT,
FOREIGN KEY (DNUM) REFERENCES department(DNUM)
);



CREATE TABLE PROJECT(
PNUMBER INT PRIMARY KEY,
PNAME NVARCHAR(50),
LOCATION NVARCHAR(50),
CITY NVARCHAR(50),
DNUM INT,
FOREIGN KEY (DNUM) REFERENCES department(DNUM)
);



CREATE TABLE WORKON(
SSN CHAR(9),
PNUMBER INT,
WORKINGHOUR INT,
FOREIGN KEY (SSN) REFERENCES employee(SSN),
FOREIGN KEY (PNUMBER) REFERENCES PROJECT(PNUMBER)
);


SELECT * FROM department;
SELECT * FROM employee
SELECT * FROM dependent
SELECT * FROM DEARTMENTLOC
SELECT * FROM PROJECT
SELECT * FROM WORKON







